[versions]
agp = "8.10.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
#activity = "1.10.1"
#appcompat = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }